dkmc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'user.views.error_404'
handler500 = 'user.views.error_500'

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

# Urls related with notice
urlpatterns += [
    path('notice', views.NoticeList.as_view(), name='user_notice'),
    path('notice/<int:pk>', views.NoticeDetail.as_view(), name='user_notice_detail'),
    path('notice/create', views.NoticeCreate.as_view(), name='user_notice_create'),
    path('notice/update/<int:pk>', views.NoticeUpdate.as_view(), name='user_notice_update'),
    path('notice/<int:pk>/delete/', views.NoticeDelete.as_view(), name='user_notice_delete'),   
]

# Urls related with events
urlpatterns += [
    path('event', views.EventList.as_view(), name='user_event'),
    path('event/<int:pk>', views.EventDetail.as_view(), name='user_event_detail'),
    path('event/create', views.EventCreate.as_view(), name='user_event_create'),
    path('event/update/<int:pk>', views.EventUpdate.as_view(), name='user_event_update'),
    path('event/<int:pk>/delete/', views.EventDelete.as_view(), name='user_event_delete'),   
]

# Urls related with contact form submission
urlpatterns += [
    path('contact', views.ContactList.as_view(), name='user_contact'),
    path('contact/<int:pk>', views.ContactDetail.as_view(), name='user_contact_detail'),
]

# Urls related with staffs
urlpatterns += [
    path('staff', views.StaffList.as_view(), name='user_staff'),
    path('staff/<int:pk>', views.StaffDetail.as_view(), name='user_staff_detail'),
    path('staff/create', views.StaffCreate.as_view(), name='user_staff_create'),
    path('staff/update/<int:pk>', views.StaffUpdate.as_view(), name='user_staff_update'),
    path('staff/<int:pk>/delete/', views.StaffDelete.as_view(), name='user_staff_delete'),   
]

pages/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    phone_no = models.CharField(max_length=100)
    message = models.TextField()
    contact_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Notice(models.Model):
    title = models.CharField(max_length=200)
    notice_type = models.CharField(max_length=100)
    location = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    notice_date = models.DateField(null=True, blank=True)
    notice_pic = models.ImageField(upload_to='notice', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('user_notice_detail', kwargs={'pk': self.pk})


class Event(models.Model):
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    event_pic = models.ImageField(upload_to='event', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('user_event_detail', kwargs={'pk': self.pk})

    @property
    def is_same_year(self):
        if self.start_date.year == self.end_date.year:
            return True

    @property
    def is_same_yearmonth(self):
        if(self.start_date.year == self.end_date.year) and (self.start_date.month == self.end_date.month):
            return True

user/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class MemberInfo(models.Model):
    name = models.CharField(max_length=200)
    post = models.CharField(max_length=30)
    member_type = models.IntegerField()
    email = models.EmailField(max_length=100, null=True, blank=True)
    phone_number = models.CharField(max_length=100, null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    photo = models.ImageField(upload_to='faculty_members',blank=True, null=True)
    additional_info = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('user_staff_detail', kwargs={'pk': self.pk})

user/forms.py
from django import forms
from pages.models import Notice, Event
from .models import MemberInfo

class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = '__all__'


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields ='__all__'


class MemberInfoForm(forms.ModelForm):
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'type':'tel'}))
    class Meta:
        model = MemberInfo
        fields ='__all__'

user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages, auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
from pages.models import Notice, Event, Contact
from .models import MemberInfo
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import NoticeForm, EventForm, MemberInfoForm


# Create your views here.
def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                # messages.success(request, 'You are now logged in')
                return redirect('dashboard')
            else:
                messages.error(request, 'Invalid Username or Password')
                return redirect('login')
        else:
            return render(request,'user/login.html')
    else:
        return redirect('dashboard')    

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        messages.success(request, 'You are now log out')
        return redirect('login')

def error_404(request, exception):
        data = {}
        return render(request,'user/404.html',data)

def error_500(request):
        data = {}
        return render(request,'user/500.html',data)

@login_required()
def dashboard(request):
    return render(request, 'user/dashboard.html')

class NoticeList(LoginRequiredMixin, ListView):
    model = Notice
    template_name = "user/notice_list.html"

class NoticeDetail(LoginRequiredMixin, DetailView):
    model = Notice
    template_name = "user/notice_detail.html"

class NoticeCreate(LoginRequiredMixin, CreateView):
    model = Notice
    form_class = NoticeForm
    template_name = "user/notice_form.html"

class NoticeUpdate(LoginRequiredMixin, UpdateView):
    model = Notice
    form_class = NoticeForm
    template_name = "user/notice_form.html"

class NoticeDelete(LoginRequiredMixin, DeleteView):
    model = Notice
    success_url = reverse_lazy('user_notice')

# Views for event handling
class EventList(LoginRequiredMixin, ListView):
    model = Event
    template_name = "user/event_list.html"

class EventDetail(LoginRequiredMixin, DetailView):
    model = Event
    template_name = "user/event_detail.html"

class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm
    template_name = "user/event_form.html"

class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm
    template_name = "user/event_form.html"

class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('user_event')


# Views for event handling
class ContactList(LoginRequiredMixin, ListView):
    model = Contact
    template_name = "user/contact_list.html"

class ContactDetail(LoginRequiredMixin, DetailView):
    model = Contact
    template_name = "user/contact_detail.html"


# Views for Staff data handling
class StaffList(LoginRequiredMixin, ListView):
    model = MemberInfo
    template_name = "user/staff_list.html"

class StaffDetail(LoginRequiredMixin, DetailView):
    model = MemberInfo
    template_name = "user/staff_detail.html"

class StaffCreate(LoginRequiredMixin, CreateView):
    model = MemberInfo
    form_class = MemberInfoForm
    template_name = "user/staff_form.html"

class StaffUpdate(LoginRequiredMixin, UpdateView):
    model = MemberInfo
    form_class = MemberInfoForm
    template_name = "user/staff_form.html"

class StaffDelete(LoginRequiredMixin, DeleteView):
    model = MemberInfo
    success_url = reverse_lazy('user_staff')

templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
        <title>Admin {% block title %}{% endblock %} </title>
        <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon"/>
        <link href="{% static 'css/user_custom.css' %}" rel="stylesheet">
        <link href="{% static 'css/user_style.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% block css %}{% endblock %}
    </head>
    <body class="app">

        {% block spinner %}
        <div id="loader">
            <div class="spinner"></div>
        </div>
        {% endblock %}
        
        <div role="main">
            <!-- Sidebar section of the site -->
            <div class="sidebar">
                <div class="sidebar-inner">
                        {% include 'user/partials/sidebar.html' %}
                </div>
            </div>

            <!-- Header section of the site -->
            <div class="page-container">
                <div class="header navbar"><div class="header-container">
                    {% include 'user/partials/header.html' %}
                </div>
            </div>

            


            <!-- Main Container of the page -->
            <main class="main-content bgc-grey-100">
                
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                        {% block breadcrumb %}{% endblock %}
                    </ol>
                </nav><br>

                <div id="mainContent">
                    {% block content %}{% endblock %}
                </div>
            </main>

            {% include 'user/partials/footer.html' %}
            </div>
        </div>
        <script>window.addEventListener('load', () => {
                const loader = document.getElementById('loader');
                setTimeout(() => {
                loader.classList.add('fadeOut');
                }, 300);
            });
        </script>
        <script type="text/javascript" src="{% static 'js/vendor.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bundle.js' %}"></script>
        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        {% block js %}{% endblock %}
    </body>
</html>

templates/user/contact_detail.html
{% extends 'user/base.html' %}

{% block title %} | Contact {% endblock%}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'user_contact' %}">Contact</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ contact.name }}</li>
{% endblock %}


{% block content %}
    
<div class="row">
<div class="col-md-3"></div>
<div class="card mb-3 col-md-6">
        <div class="card-body">
          <h3 class="card-title">{{ contact.name }}</h3><hr>
          <p class="card-text"><b>Phone No.: </b> {{ contact.phone_no }}</p>
          <p class="card-text"><b>Email: </b> {{ contact.email }}</p>
          <p class="card-text float-left"><small class="text-muted">Submitted On: {{ contact.contact_date|timesince }} ago</small></p>
        </div>
        <div class="card-footer mb-3">
            <h4 class="card-title">Message:</h4>
            <p class="card-title">{{ contact.message }}</p>
        </div>
      </div>
    </div>

{% endblock %}

templates/user/contact_list.html
{% extends 'user/base.html' %}

{% block title %} | Contact {% endblock%}

{% block breadcrumb %}
<li class="breadcrumb-item active" aria-current="page">Contact</li>
{% endblock %}


{% block content %}
<div class="col-md-12">
    <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <div class="row">
            <div class="col-md-9"><h3 class="c-grey-900 mB-20">List of Messages Submitted from the Contact-Us page</h3></div>
        </div><hr>
        <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead><tr>
                <th>S.N</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Message</th>
                <th>Submitted Date</th>
            </tr></thead>
            <tbody>
                {% if object_list %}        
                    {% for contact in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'user_contact_detail' contact.id %}">{{ contact.name }}</a></td>
                        <td>{{ contact.email }}</td>
                        <td>{{ contact.phone_no }}</td>
                        <td>{{ contact.message|truncatechars:50}}</td>
                        <td>{{ contact.contact_date }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                   <h4 class="c-red-500"> No one has try to contact through the site </h4>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/user/dashboard.html
{% extends 'user/base.html' %}

{% block title %} | Dashboard {% endblock%}

{% block content %}

<h4>Admin Dashboard Area</h4>

{% endblock %}

templates/user/event_detail.html
{% extends 'user/base.html' %}
{% load static %}

{% block title %} | Events {% endblock%}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'user_event' %}">Event</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ event.title }}</li>
{% endblock %}


{% block content %}
    
    <div class="col-md-9 text-right">
        <a href="{% url 'user_event_update' event.id %}"><button class="btn btn-success">Update Event</button></a>
        <a class="confirm-delete"><button class="btn btn-danger">Delete Event</button></a>
        <form method="post" action="{% url 'user_event_delete' event.id %}" id="delete_form">
            {% csrf_token %}
            <input type="hidden">
        </form>
    </div>
    <div class="row">
    <div class="col-md-3"></div>
    <div class="card mb-3 col-md-6">
            {% if event.event_pic %}
                <img class="card-img-top mt-3" src="{{ event.event_pic.url }}" alt="Card image cap" height="420">
            {% else %}
                <img class="card-img-top mt-3" src="{% static 'img/events.png' %}" alt="Card image cap" height="420">
            {% endif %}
            <div class="card-body">
              <h3 class="card-title">{{ event.title }}</h3>
              <p class="card-text">{{ event.description }}</p>
              <h6 class="card-text text-primary">Location: {{ event.location }}</h6>
              <p class="card-text float-left"><small class="text-muted">Created {{ event.created_date|timesince }} ago</small></p>
              {% if event.created_date != event.updated_date %}
                <p class="card-text float-right"><small class="text-muted">Updated {{ event.updated_date|timesince }} ago</small></p>
              {% endif %}
            </div>
            <div class="card-footer mb-3">
                <p class="card-title"><b>Event held Date and Time</b></p>
                <p class="card-text"><b>Date:</b> &nbsp; {{ event.start_date }} - {{ event.end_date }}</p>
                <p class="card-text"><b>Time:</b> &nbsp; {{ event.start_time }} - {{ event.end_time }}</p>
            </div>
          </div>
        </div>

{% endblock %}


{% block js %}
<script>
    $(document).on('click', '.confirm-delete', function(){
        ans = confirm('Are you sure you want to delete this?');
        if(ans==true){
            $('#delete_form').submit();
        } else{
            return false;
        }
    });
</script>
{% endblock %}

templates/user/event_form.html
{% extends 'user/base.html' %}
{% load crispy_forms_tags %}

{% block title %} | Events {% endblock%}

{% block css %}
<style>
    form label{
        font-weight: bold;
    }
</style>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'user_event' %}">Event</a></li>
    {% if '/update/' in request.path %}
        <li class="breadcrumb-item"><a href="{% url 'user_event_detail' object.id %}">{{ object.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Event</li>
    {% endif %}
{% endblock %}



{% block content %}
    <form method="post" class="pl-4 pr-4" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-5">
                {{ form.title|as_crispy_field }}
            </div>
            <div class="col-md-1"></div>
            <div class="form-group col-md-4">
                {{ form.location|as_crispy_field }}
            </div>
            <div class="form-group col-md-4">
                {{ form.start_date|as_crispy_field }}
                {{ form.start_time|as_crispy_field }}
            </div>
            <div class="col-md-2"></div>
            <div class="form-group col-md-4">
                {{ form.end_date|as_crispy_field }}
                {{ form.end_time|as_crispy_field }}
            </div>
        </div>
        {{ form.description|as_crispy_field }}
        {{ form.event_pic|as_crispy_field }}<br>
        <span>* are required fields</span><br><br>
        <div class="text-center"><button type="submit" class="btn btn-success">
            {% if '/update/' in request.path %}Update Event{% else %}Create Event{% endif %}
        </button></div>
    </form>
{% endblock %}

{% block js %}
<script>
    $('#id_start_date').attr("type","date");
    $('#id_start_time').attr("type","time");
    $('#id_end_date').attr("type","date");
    $('#id_end_time').attr("type","time");
</script>
{% endblock %}

templates/user/event_list.html
{% extends 'user/base.html' %}

{% block title %} | Events {% endblock%}

{% block breadcrumb %}
<li class="breadcrumb-item active" aria-current="page">Event</li>
{% endblock %}


{% block content %}
<div class="col-md-12">
    <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <div class="row">
            <div class="col-md-9"><h3 class="c-grey-900 mB-20">All Event List</h3></div>
            <div class="col-md-3 text-right"><a href="{% url 'user_event_create' %}"><button type="button" class="btn cur-p btn-primary">Create New Event</button></a></div>
        </div><hr>
        <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead><tr>
                <th>S.N</th>
                <th>Title</th>
                <th>Location</th>
                <th>Description</th>
                <th>Event Date</th>
                <th>Event Time</th>
                <th>Created Date</th>
                <th>Updated Date</th>
            </tr></thead>
            <tbody>
                {% if object_list %}        
                    {% for event in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'user_event_detail' event.id %}">{{ event.title }}</a></td>
                        <td>{{ event.location }}</td>
                        <td>{{ event.description|truncatechars:50}}</td>
                        <td>{{ event.start_date }} - {{ event.end_date }}</td>
                        <td>{{ event.start_time }} - {{ event.end_time }}</td>
                        <td>{{ event.created_date }}</td>
                        <td>{{ event.updated_date }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                   <h4 class="c-red-500"> There are no event to display. You can create event from here </h4>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/user/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>DKMC | Login</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">
    <link href="{% static 'css/user_custom.css' %}" rel="stylesheet">
  </head>
  <body>
    <form method="POST" action="{% url 'login' %}" class="form-signin">
        <div class="text-center mb-4">
            <img class="mb-4" src="{% static 'img/logo1.png' %}" alt="Logo" width="250" height="65">
            <h1 class="h3 mb-3 font-weight-normal">Admin Login</h1>
        </div>
        {% include 'components/alerts.html' %}
        {% csrf_token %}
        <div class="form-label-group">
            <input type="text" id="inputUsername" class="form-control" name="username" placeholder="User Name" required autofocus>
            <label for="inputUsername">User Name</label>
        </div>

        <div class="form-label-group">
            <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Password" required>
            <label for="inputPassword">Password</label>
        </div>

        <div class="checkbox mb-3">
            <label><input type="checkbox" value="remember-me"> Remember me</label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
        setTimeout( function(){
            $('#message').fadeOut('slow');
        }, 3000);
    </script>
</body>
</html>

templates/user/notice_form.html
{% extends 'user/base.html' %}
{% load crispy_forms_tags %}

{% block title %} | Notices {% endblock%}

{% block css %}
<style>
    form label{
        font-weight: bold;
    }
</style>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'user_notice' %}">Notice</a></li>
    {% if '/update/' in request.path %}
        <li class="breadcrumb-item"><a href="{% url 'user_notice_detail' object.id %}">{{ object.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Notice</li>
    {% endif %}
{% endblock %}



{% block content %}
    <form method="post" class="pl-4 pr-4" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-5">
                {{ form.title|as_crispy_field }}
            </div>
            <div class="col-md-1"></div>
            <div class="form-group col-md-4">
                {{ form.location|as_crispy_field }}
            </div>
            <div class="form-group col-md-4">
                <label for="id_notice_type">Type*</label>
                <select id="id_notice_type" class="form-control"name="notice_type" required>
                    <option value="">Choose...</option>
                    <option value="Exam Notice" {% if object.notice_type == 'Exam Notice' %}selected{% endif %}>Exam Notice</option>
                    <option value="Holiday Notice" {% if object.notice_type == 'Holiday Notice' %}selected{% endif %}>Holiday Notice</option>
                    <option value="Fee Notice" {% if object.notice_type == 'Fee Notice' %}selected{% endif %}>Fee Notice</option>
                    <option value="Program Notice" {% if object.notice_type == 'Program Notice' %}selected{% endif %}>Program Notice</option>
                </select>
            </div>
            <div class="col-md-2"></div>
            <div class="form-group col-md-4">
                <label for="id_notice_date">Notice Date</label>
                <input type="date" class="form-control" id="id_notice_date" name="notice_date" value="{{ object.notice_date|date:"Y-m-d"}}">
            </div>
        </div>
        {{ form.description|as_crispy_field }}
        {{ form.notice_pic|as_crispy_field }}<br>
        <span>* are required fields</span><br><br>
        <div class="text-center"><button type="submit" class="btn btn-success">
            {% if '/update/' in request.path %}Update Notice{% else %}Create Notice{% endif %}
        </button></div>
    </form>
{% endblock %}

templates/user/notice_list.html
{% extends 'user/base.html' %}

{% block title %} | Notices {% endblock%}

{% block breadcrumb %}
<li class="breadcrumb-item active" aria-current="page">Notice</li>
{% endblock %}


{% block content %}
<div class="col-md-12">
    <div class="bgc-white bd bdrs-3 p-20 mB-20">
        <div class="row">
            <div class="col-md-9"><h3 class="c-grey-900 mB-20">All Notice List</h3></div>
            <div class="col-md-3 text-right"><a href="{% url 'user_notice_create' %}"><button type="button" class="btn cur-p btn-primary">Create New Notice</button></a></div>
        </div><hr>
        <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead><tr>
                <th>S.N</th>
                <th>Title</th>
                <th>Type</th>
                <th>Location</th>
                <th>Description</th>
                <th>Notice Date</th>
                <th>Created Date</th>
                <th>Updated Date</th>
            </tr></thead>
            <tbody>
                {% if object_list %}        
                    {% for notice in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'user_notice_detail' notice.id %}">{{ notice.title }}</a></td>
                        <td>{{ notice.notice_type }}</td>
                        <td>{{ notice.location }}</td>
                        <td>{{ notice.description|truncatechars:50}}</td>
                        <td>{{ notice.notice_date }}</td>
                        <td>{{ notice.created_date }}</td>
                        <td>{{ notice.updated_date }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                   <h4 class="c-red-500"> There are no notice to display. You can create notice from here </h4>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/user/staff_form.html
{% extends 'user/base.html' %}
{% load crispy_forms_tags %}

{% block title %} | Staffs {% endblock%}

{% block css %}
<style>
    form label{
        font-weight: bold;
    }
</style>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'user_staff' %}">Staff</a></li>
    {% if '/update/' in request.path %}
        <li class="breadcrumb-item"><a href="{% url 'user_staff_detail' object.id %}">{{ object.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    {% else %}
        <li class="breadcrumb-item active" aria-current="page">Create New Staff</li>
    {% endif %}
{% endblock %}



{% block content %}
    <form method="post" class="pl-4 pr-4" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row" style="margin-left: 8em;">
            <div class="form-group col-md-5">
                {{ form.name|as_crispy_field }}
            </div>
            <div class="col-md-1"></div>
            <div class="form-group col-md-4">
                {{ form.post|as_crispy_field }}
            </div>
            <div class="form-group col-md-4">
                {{ form.email|as_crispy_field }}
            </div>
            <div class="col-md-2"></div>
            <div class="form-group col-md-4">
                {{ form.phone_number|as_crispy_field }}
            </div>
            <div class="form-group col-md-4">
                    <label for="id_member_type">Staff Type*</label>
                    <select id="id_member_type" class="form-control" name="member_type" required>
                        <option value="">Choose...</option>
                        <option value="1" {% if object.member_type == 1 %}selected{% endif %}>Faculty Member</option>
                        <option value="2" {% if object.member_type == 2 %}selected{% endif %}>Non-Academic Staff</option>
                    </select>
            </div>
            <div class="form-group col-md-10">
                {{ form.about|as_crispy_field }}
            </div>
            <div class="form-group col-md-4">
                {{ form.photo|as_crispy_field }}
            </div>
            <div class="form-group col-md-10">
                {{ form.additional_info|as_crispy_field }}
            </div>
            <div class="col-md-4"><span>* are required fields</span></div>
        </div>
        <br><br>
        <div class="text-center"><button type="submit" class="btn btn-success">
            {% if '/update/' in request.path %}Update Staff{% else %}Create Staff{% endif %}
        </button></div>
    </form>
{% endblock %}